### ISSUE TITLE
Filtering crashes when a Image column select

### ISSUE THREAD

**Issue by farshadvl** [davidegironi/advanceddatagridview#144]
Hi
I recently have problems with Image columns in ADGV.
Is there any way to avoid it and prevent user to filter image columns or handle it?

this the error:

> System.InvalidOperationException
  HResult=0x80131509
  Message=Failed to compare two elements in the array.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource, Exception e)
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   at System.MemoryExtensions.Sort[T](Span`1 span, Comparison`1 comparison)
   at System.Linq.EnumerableSorter`2.QuickSort(Int32[] keys, Int32 lo, Int32 hi)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__17.MoveNext()
   at Zuby.ADGV.MenuStrip.BuildNodes(IEnumerable`1 vals, DataGridView dataGridView, String columnName)
   at Zuby.ADGV.MenuStrip.Show(Control control, Int32 x, Int32 y, String columnName)
   at Zuby.ADGV.AdvancedDataGridView.Cell_FilterPopup(Object sender, ColumnHeaderCellEventArgs e)
   at Zuby.ADGV.ColumnHeaderCell.OnMouseUp(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridViewCell.OnMouseUpInternal(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellMouseUp(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at PDMA.Forms.Program.Main() in D:\Source\KianSazehPiping\KianSazehPiping\Program.cs:line 21

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentException: At least one object must implement IComparable.

**Comment by davidegironi** [comment]
Hi @farshadvl
I'm not able to reproduce it using the sample project you can find here.
Can you please provide an working example, or step procedure to replicate this issue? Please start from the sample project here.
